language: ruby
rvm:
- 2.3.3

before_install:
- nvm install stable

install: 
- gem install bundler jekyll
- npm install -g firebase-tools
script: 
- bundle install
- bundle exec jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

after_success:
   - firebase deploy --token ${FIREBASE_TOKEN}
