---
title: River Church
collections:
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  sermons:
    title: Sermons
    output: true
  teachings:
    title: Teachings
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: sermons
  values:
    layout: sermon
    image: 'https://riverbrockport.com/uploads/RIVERxchurch-1.jpg'
    video_id:
    - none
    audio_id:
    - none
    verses:
    - none
    summary: Check us out online at https://riverbrockport.com!
- scope:
    path: ''
    type: events
  values:
    description: Awesome Event!
    image: ''
- scope:
    path: ''
    type: pages
  values:
    layout: page
    header-image: ''
- scope:
    path: ''
    type: teachings
  values:
    layout: blog
    author: Jeremiah Thomas
    subtitle: Subtitle
    image: ''
- scope:
    path: ''
    type: posts
  values:
    layout: blog
    author: Jeremiah Thomas
    subtitle: Subtitle
    image: ''
description: A Family Focused - Spirit Filled Church In Brockport, NY
url: https://riverbrockport.com
baseurl: 
logo: uploads/RIVERxchurch-1.jpg
email: contact@riverbrockport.com
social:
- title: facebook
  url: https://fb.me/riverbrockport/
- title: youtube-play
  url: https://youtube.com/channel/UC4Fq1AHEsxanWWibB0lPZ8A/
- title: instagram
  url: https://instagram.com/riverbrockport/
- title: podcast
  url: https://geo.itunes.apple.com/us/podcast/river-rochester/id1182211082?mt=2/
address:
- line: 101 Kenyon St
- line: Brockport, NY 14420
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
sass:
  sass_dir: assets/css/_sass
  style: compressed
permalink: none
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
